apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: glfiix3v3-java-springboot-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/glfiix3v3-java-springboot